<?php
defined( 'ABSPATH' ) || exit;

final class TAB_Admin {
	public static function boot(){add_action('admin_menu',array(__CLASS__,'menu'));add_action('admin_init',array(__CLASS__,'save'));add_action('admin_enqueue_scripts',array(__CLASS__,'assets'));}
	public static function menu(){add_menu_page('TeleAdmin Bridge','TeleAdmin','manage_options','teleadmin-bridge',array(__CLASS__,'page'),'dashicons-format-chat',58);}
	public static function assets($hook){if('toplevel_page_teleadmin-bridge'===$hook)wp_enqueue_style('tab-admin',TAB_URL.'assets/admin.css',array(),TAB_VERSION);}
	public static function save(){
		if(empty($_POST['tab_action'])||!current_user_can('manage_options'))return;check_admin_referer('tab_save');$a=sanitize_key(wp_unslash($_POST['tab_action']));$s=TAB_Plugin::settings();
		if('save_bot'===$a){$s['bot_token']=trim(sanitize_text_field(wp_unslash($_POST['bot_token']??'')));$s['language']=in_array($_POST['language']??'',array('fa','en'),true)?$_POST['language']:'fa';update_option(TAB_Plugin::OPTION,$s,false);$me=TAB_Telegram::request('getMe');if(is_wp_error($me)){add_settings_error('tab','api',$me->get_error_message(),'error');}else{$s['bot_username']=sanitize_text_field($me['username']);update_option(TAB_Plugin::OPTION,$s,false);$configured=self::configure($s);if(is_wp_error($configured))add_settings_error('tab','hook',$configured->get_error_message(),'error');else add_settings_error('tab','saved',self::t(self::lang(),'configured'),'success');}}
		if('save_integrations'===$a){$s['notify_orders']=empty($_POST['notify_orders'])?0:1;$s['notify_invoices']=empty($_POST['notify_invoices'])?0:1;update_option(TAB_Plugin::OPTION,$s,false);add_settings_error('tab','saved',self::t(self::lang(),'saved'),'success');}
		if('disconnect'===$a){delete_user_meta(get_current_user_id(),'tab_telegram_chat_id');delete_user_meta(get_current_user_id(),'tab_telegram_username');delete_user_meta(get_current_user_id(),'tab_flow');add_settings_error('tab','disconnected',self::t(self::lang(),'disconnected'),'success');}
	}
	private static function configure($s){$url=rest_url('teleadmin/v1/webhook/'.$s['secret']);$r=TAB_Telegram::request('setWebhook',array('url'=>$url,'secret_token'=>$s['secret'],'allowed_updates'=>wp_json_encode(array('message'))));if(is_wp_error($r))return $r;TAB_Telegram::request('setMyCommands',array('commands'=>wp_json_encode(array(array('command'=>'start','description'=>'Open admin menu'),array('command'=>'status','description'=>'Site status'),array('command'=>'cancel','description'=>'Cancel current process')))));TAB_Telegram::request('setMyName',array('name'=>mb_substr(wp_specialchars_decode(get_bloginfo('name')),0,64)));return true;}
	private static function lang(){if(isset($_GET['ui_lang'])&&in_array($_GET['ui_lang'],array('fa','en'),true)){update_user_meta(get_current_user_id(),'tab_admin_language',sanitize_key($_GET['ui_lang']));}return get_user_meta(get_current_user_id(),'tab_admin_language',true)==='en'?'en':'fa';}
	public static function page(){
		$l=self::lang();$rtl='fa'===$l;$s=TAB_Plugin::settings();$chat=get_user_meta(get_current_user_id(),'tab_telegram_chat_id',true);$username=get_user_meta(get_current_user_id(),'tab_telegram_username',true);$tab=in_array($_GET['section']??'',array('bot','connection','integrations'),true)?$_GET['section']:'bot';
		$code=wp_generate_password(24,false,false);set_transient('tab_pair_'.sanitize_key($code),array('user_id'=>get_current_user_id()),10*MINUTE_IN_SECONDS);$deep=!empty($s['bot_username'])?'https://t.me/'.rawurlencode($s['bot_username']).'?start=connect_'.rawurlencode($code):'';
		$base=admin_url('admin.php?page=teleadmin-bridge');settings_errors('tab');?>
		<div class="wrap tab-wrap <?php echo $rtl?'tab-rtl':''; ?>">
		<header><div class="tab-brand"><div class="tab-logo">T</div><div><h1>TeleAdmin Bridge</h1><p><?php echo esc_html(self::t($l,'subtitle'));?></p></div></div><div class="tab-head-actions"><a class="tab-lang" href="<?php echo esc_url(add_query_arg(array('ui_lang'=>$rtl?'en':'fa','section'=>$tab),$base));?>"><?php echo $rtl?'English':'فارسی';?></a><span class="tab-pill <?php echo $chat?'ok':'';?>"><?php echo esc_html(self::t($l,$chat?'connected':'not_connected'));?></span></div></header>
		<nav class="tab-nav"><a class="<?php echo 'bot'===$tab?'active':'';?>" href="<?php echo esc_url(add_query_arg('section','bot',$base));?>">⚙️ <?php echo esc_html(self::t($l,'bot_tab'));?></a><a class="<?php echo 'connection'===$tab?'active':'';?>" href="<?php echo esc_url(add_query_arg('section','connection',$base));?>">🔐 <?php echo esc_html(self::t($l,'connection_tab'));?></a><a class="<?php echo 'integrations'===$tab?'active':'';?>" href="<?php echo esc_url(add_query_arg('section','integrations',$base));?>">🔌 <?php echo esc_html(self::t($l,'integrations_tab'));?></a></nav>
		<?php if('bot'===$tab):?><div class="tab-grid"><section class="tab-card wide"><span class="tab-step">01</span><h2><?php echo esc_html(self::t($l,'bot_title'));?></h2><p><?php echo esc_html(self::t($l,'bot_help'));?></p><form method="post"><?php wp_nonce_field('tab_save');?><input type="hidden" name="tab_action" value="save_bot"><div class="tab-field"><label>BotFather Token</label><input class="regular-text code" dir="ltr" type="password" autocomplete="new-password" name="bot_token" value="<?php echo esc_attr($s['bot_token']);?>" placeholder="123456789:AA..."></div><div class="tab-field"><label><?php echo esc_html(self::t($l,'bot_language'));?></label><select name="language"><option value="fa" <?php selected($s['language'],'fa');?>>فارسی</option><option value="en" <?php selected($s['language'],'en');?>>English</option></select></div><?php submit_button(self::t($l,'save_config'),'primary large');?></form></section><section class="tab-card wide tab-info"><h3>💡 <?php echo esc_html(self::t($l,'requirements'));?></h3><p><?php echo esc_html(self::t($l,'https_help'));?></p></section></div>
		<?php elseif('connection'===$tab):?><div class="tab-grid"><section class="tab-card wide tab-connect"><span class="tab-step">02</span><h2><?php echo esc_html(self::t($l,'connect_title'));?></h2><?php if($chat):?><div class="tab-connected-box"><div class="tab-check">✓</div><div><strong><?php echo esc_html(self::t($l,'connected_ok'));?></strong><p dir="ltr"><?php echo $username?'@'.esc_html($username):esc_html($chat);?></p></div></div><form method="post"><?php wp_nonce_field('tab_save');?><input type="hidden" name="tab_action" value="disconnect"><?php submit_button(self::t($l,'disconnect'),'secondary');?></form><?php elseif($deep):?><p><?php echo esc_html(self::t($l,'pair_help'));?></p><a class="button button-primary button-hero" href="<?php echo esc_url($deep);?>" target="_blank" rel="noopener noreferrer">✈️ <?php echo esc_html(self::t($l,'connect_button'));?></a><p class="description"><?php echo esc_html(self::t($l,'expires'));?></p><?php else:?><div class="tab-warning"><?php echo esc_html(self::t($l,'save_first'));?></div><?php endif;?></section></div>
		<?php else:?><div class="tab-grid"><section class="tab-card wide"><span class="tab-step">03</span><h2><?php echo esc_html(self::t($l,'integrations_title'));?></h2><div class="tab-status"><span>WordPress <b>✓</b></span><span>WooCommerce <b class="<?php echo class_exists('WooCommerce')?'on':'off';?>"><?php echo class_exists('WooCommerce')?'✓':'—';?></b></span><span>Tahanoa Invoice <b class="<?php echo class_exists('EZINV_DB')?'on':'off';?>"><?php echo class_exists('EZINV_DB')?'✓':'—';?></b></span><span>Telegram Webhook <b class="<?php echo !empty($s['bot_username'])?'on':'off';?>"><?php echo !empty($s['bot_username'])?'✓':'—';?></b></span></div><form method="post" class="tab-toggles"><?php wp_nonce_field('tab_save');?><input type="hidden" name="tab_action" value="save_integrations"><label><input type="checkbox" name="notify_orders" value="1" <?php checked($s['notify_orders']);?>><span><strong><?php echo esc_html(self::t($l,'order_notifications'));?></strong><small><?php echo esc_html(self::t($l,'order_help'));?></small></span></label><label><input type="checkbox" name="notify_invoices" value="1" <?php checked($s['notify_invoices']);?>><span><strong><?php echo esc_html(self::t($l,'invoice_notifications'));?></strong><small><?php echo esc_html(self::t($l,'invoice_help'));?></small></span></label><?php submit_button(self::t($l,'save_settings'),'primary large');?></form></section></div><?php endif;?>
		<footer><?php echo esc_html(self::t($l,'security_note'));?></footer></div><?php
	}
	private static function t($l,$k){$x=array(
	'subtitle'=>array('مدیریت امن وردپرس از طریق تلگرام','Secure WordPress administration through Telegram'),'connected'=>array('مدیر متصل است','Admin connected'),'not_connected'=>array('متصل نشده','Not connected'),'bot_tab'=>array('پیکربندی ربات','Bot configuration'),'connection_tab'=>array('اتصال مدیر','Administrator connection'),'integrations_tab'=>array('یکپارچه‌سازی‌ها','Integrations'),'bot_title'=>array('پیکربندی BotFather','BotFather configuration'),'bot_help'=>array('توکن ربات را وارد کنید؛ Webhook امن، نام سایت و فرمان‌های ربات به‌صورت خودکار تنظیم می‌شوند.','Enter the bot token; the secure webhook, site name, and commands are configured automatically.'),'bot_language'=>array('زبان پیش‌فرض ربات','Default bot language'),'save_config'=>array('ذخیره و پیکربندی ربات','Save and configure bot'),'requirements'=>array('پیش‌نیاز اتصال','Connection requirement'),'https_help'=>array('سایت باید HTTPS معتبر و REST API قابل دسترس از اینترنت داشته باشد.','The site needs valid HTTPS and a REST API reachable from the internet.'),'connect_title'=>array('اتصال حساب مدیر وردپرس','Connect a WordPress administrator'),'connected_ok'=>array('حساب تلگرام این مدیر با موفقیت متصل است.','This administrator’s Telegram account is connected.'),'disconnect'=>array('قطع اتصال حساب من','Disconnect my account'),'pair_help'=>array('با دکمه زیر وارد ربات شوید تا حساب مدیر فعلی به‌صورت امن متصل شود.','Open the bot with the button below to securely connect the current administrator.'),'connect_button'=>array('اتصال با تلگرام','Connect with Telegram'),'expires'=>array('این پیوند یک‌بارمصرف است و پس از ۱۰ دقیقه منقضی می‌شود.','This one-time link expires after 10 minutes.'),'save_first'=>array('ابتدا در بخش پیکربندی، توکن معتبر ربات را ذخیره کنید.','First save a valid bot token in Bot configuration.'),'integrations_title'=>array('وضعیت و اعلان‌های یکپارچه‌سازی','Integration status and notifications'),'order_notifications'=>array('اعلان سفارش‌های ووکامرس','WooCommerce order notifications'),'order_help'=>array('سفارش جدید و تغییر وضعیت سفارش برای مدیران متصل ارسال شود.','Send new orders and status changes to connected administrators.'),'invoice_notifications'=>array('اعلان پرداخت صورتحساب','Invoice payment notifications'),'invoice_help'=>array('پرداخت موفق صورتحساب Tahanoa برای مدیران متصل ارسال شود.','Send successful Tahanoa invoice payments to connected administrators.'),'save_settings'=>array('ذخیره تنظیمات اعلان‌ها','Save notification settings'),'security_note'=>array('🔒 فقط مدیرانی که دسترسی manage_options دارند می‌توانند متصل شوند یا فرمان اجرا کنند.','🔒 Only administrators with manage_options can connect or execute commands.'),'configured'=>array('ربات و Webhook با موفقیت پیکربندی شدند.','Bot and webhook configured successfully.'),'saved'=>array('تنظیمات ذخیره شد.','Settings saved.'),'disconnected'=>array('اتصال حساب مدیر قطع شد.','Administrator account disconnected.'));return $x[$k]['fa'===$l?0:1]??$k;}
}
