<?php
defined('ABSPATH')||exit;

final class TAB_REST {
	public static function boot(){add_action('rest_api_init',array(__CLASS__,'routes'));}
	public static function routes(){register_rest_route('teleadmin/v1','/webhook/(?P<secret>[A-Za-z0-9]+)',array('methods'=>'POST','callback'=>array(__CLASS__,'webhook'),'permission_callback'=>array(__CLASS__,'authorize')));}
	public static function authorize(WP_REST_Request $r){$s=TAB_Plugin::settings();$h=(string)$r->get_header('X-Telegram-Bot-Api-Secret-Token');return !empty($s['secret'])&&hash_equals($s['secret'],(string)$r['secret'])&&hash_equals($s['secret'],$h);}
	public static function webhook(WP_REST_Request $r){$u=$r->get_json_params();if(!is_array($u)||empty($u['update_id']))return new WP_REST_Response(array('ok'=>false),400);$k='tab_update_'.absint($u['update_id']);if(get_transient($k))return array('ok'=>true);set_transient($k,1,DAY_IN_SECONDS);self::handle($u);return array('ok'=>true);}
	private static function handle($u){
		if(!empty($u['callback_query'])){self::callback($u['callback_query']);return;}
		$m=$u['message']??array();$chat=isset($m['chat']['id'])?(string)$m['chat']['id']:'';$text=isset($m['text'])?trim(sanitize_text_field($m['text'])):'';if(!$chat)return;
		if(0===strpos($text,'/start connect_')){self::connect($chat,substr($text,15),$m);return;}
		$user=self::user($chat);if(!$user){TAB_Telegram::send($chat,'Access denied. Connect from WordPress administration.');return;}$lang=self::lang($user);
		if(in_array($text,array('/start','/menu'),true)){delete_user_meta($user->ID,'tab_flow');TAB_Telegram::send($chat,self::t($lang,'menu'),TAB_Telegram::menu($lang));return;}
		if('/status'===$text){self::status($chat,$lang);return;}
		if('/cancel'===$text){delete_user_meta($user->ID,'tab_flow');TAB_Telegram::send($chat,self::t($lang,'cancelled'),TAB_Telegram::menu($lang));return;}
		$f=get_user_meta($user->ID,'tab_flow',true);if(is_array($f)&&'product'===$f['type']){TAB_Product_Flow::message($user,$chat,$m,$lang,$f);return;}
		if(is_array($f)&&'invoice'===$f['type']){self::invoice_message($user,$chat,$text,$lang,$f);return;}
		TAB_Telegram::send($chat,self::t($lang,'menu'),TAB_Telegram::menu($lang));
	}
	private static function callback($q){
		$id=sanitize_text_field($q['id']??'');$data=sanitize_text_field($q['data']??'');$chat=isset($q['message']['chat']['id'])?(string)$q['message']['chat']['id']:'';if($id)TAB_Telegram::answer_callback($id);if(!$chat)return;$user=self::user($chat);if(!$user){TAB_Telegram::send($chat,'Access denied.');return;}$lang=self::lang($user);
		if('menu:status'===$data){self::status($chat,$lang);return;}if('menu:orders'===$data){self::orders($chat,$lang);return;}
		if('product:new'===$data){TAB_Product_Flow::start($user,$chat,$lang,'new');return;}if('product:edit'===$data){TAB_Product_Flow::start($user,$chat,$lang,'edit');return;}
		if('invoice:new'===$data){self::invoice_start($user,$chat,$lang);return;}
		if(0===strpos($data,'lang:')){$lang='en'===substr($data,5)?'en':'fa';update_user_meta($user->ID,'tab_language',$lang);delete_user_meta($user->ID,'tab_flow');TAB_Telegram::send($chat,self::t($lang,'menu'),TAB_Telegram::menu($lang));return;}
		$f=get_user_meta($user->ID,'tab_flow',true);if(0===strpos($data,'pf:')&&is_array($f)&&'product'===$f['type']){TAB_Product_Flow::callback($user,$chat,$lang,$f,substr($data,3),absint($q['message']['message_id']??0));return;}
		if(0===strpos($data,'inv:')&&is_array($f)&&'invoice'===$f['type'])self::invoice_callback($user,$chat,$lang,$f,substr($data,4));
	}
	private static function invoice_start($user,$chat,$lang){if(!class_exists('EZINV_DB')){TAB_Telegram::send($chat,self::t($lang,'invoice_missing'),TAB_Telegram::menu($lang));return;}self::save_invoice($user->ID,'title',array());self::invoice_prompt($chat,$lang,'title');}
	private static function invoice_message($user,$chat,$text,$lang,$f){$d=$f['data'];$s=$f['step'];if('title'===$s){if(mb_strlen($text)<2){TAB_Telegram::send($chat,self::t($lang,'bad_title'));return;}$d['title']=sanitize_text_field($text);self::save_invoice($user->ID,'amount',$d);self::invoice_prompt($chat,$lang,'amount');return;}if('amount'===$s){$v=self::number($text);if(!$v){TAB_Telegram::send($chat,self::t($lang,'bad_amount'));return;}$d['amount']=$v;self::save_invoice($user->ID,'customer',$d);self::invoice_prompt($chat,$lang,'customer');return;}if('customer'===$s){$d['customer']=sanitize_text_field($text);self::save_invoice($user->ID,'mobile',$d);self::invoice_prompt($chat,$lang,'mobile');return;}if('mobile'===$s){$v=preg_replace('/[^0-9+]/','',$text);if(!preg_match('/^\+?[0-9]{10,15}$/',$v)){TAB_Telegram::send($chat,self::t($lang,'bad_mobile'));return;}$d['mobile']=$v;self::save_invoice($user->ID,'description',$d);self::invoice_prompt($chat,$lang,'description');return;}if('description'===$s){$d['description']=sanitize_textarea_field($text);self::save_invoice($user->ID,'confirm',$d);self::invoice_review($chat,$lang,$d);}}
	private static function invoice_callback($user,$chat,$lang,$f,$a){if('menu'===$a){delete_user_meta($user->ID,'tab_flow');TAB_Telegram::send($chat,self::t($lang,'menu'),TAB_Telegram::menu($lang));return;}if('cancel'===$a){delete_user_meta($user->ID,'tab_flow');TAB_Telegram::send($chat,self::t($lang,'cancelled'),TAB_Telegram::menu($lang));return;}if('skip'===$a){$map=array('customer'=>'mobile','mobile'=>'description','description'=>'confirm');$f['data'][$f['step']]='';$next=$map[$f['step']]??$f['step'];self::save_invoice($user->ID,$next,$f['data']);if('confirm'===$next)self::invoice_review($chat,$lang,$f['data']);else self::invoice_prompt($chat,$lang,$next);return;}if('back'===$a){$map=array('amount'=>'title','customer'=>'amount','mobile'=>'customer','description'=>'mobile','confirm'=>'description');$next=$map[$f['step']]??'title';self::save_invoice($user->ID,$next,$f['data']);self::invoice_prompt($chat,$lang,$next);return;}if('confirm'===$a){self::invoice_create($user,$chat,$lang,$f['data']);}}
	private static function invoice_prompt($chat,$lang,$step){$skip=in_array($step,array('customer','mobile','description'),true);$row=array();if($skip)$row[]=array('text'=>self::t($lang,'skip'),'callback_data'=>'inv:skip');if('title'!==$step)$row[]=array('text'=>self::t($lang,'back'),'callback_data'=>'inv:back');$row[]=array('text'=>self::t($lang,'cancel'),'callback_data'=>'inv:cancel');$menu='fa'===$lang?'بازگشت به منو':'Back to menu';TAB_Telegram::send($chat,self::t($lang,'inv_'.$step),TAB_Telegram::inline(array($row,array(array('text'=>$menu,'callback_data'=>'inv:menu')))));}
	private static function invoice_review($chat,$lang,$d){$text=self::t($lang,'review')."\n".$d['title']."\n".number_format($d['amount'])." ".self::t($lang,'toman');$kb=TAB_Telegram::inline(array(array(array('text'=>self::t($lang,'confirm'),'callback_data'=>'inv:confirm')),array(array('text'=>self::t($lang,'back'),'callback_data'=>'inv:back'),array('text'=>self::t($lang,'cancel'),'callback_data'=>'inv:cancel'))));TAB_Telegram::send($chat,$text,$kb);}
	private static function invoice_create($user,$chat,$lang,$d){if(!class_exists('EZINV_DB')){TAB_Telegram::send($chat,self::t($lang,'invoice_missing'));return;}$token=bin2hex(random_bytes(24));$now=current_time('mysql');$id=EZINV_DB::insert_invoice(array('token'=>$token,'title'=>$d['title'],'customer_name'=>$d['customer']??'','mobile'=>$d['mobile']??'','email'=>'','items_json'=>null,'subtotal_irr'=>$d['amount']*10,'shipping_irr'=>0,'amount_irr'=>$d['amount']*10,'description'=>$d['description']??'','status'=>'pending','created_at'=>$now,'updated_at'=>$now));if(is_wp_error($id)){TAB_Telegram::send($chat,$id->get_error_message());return;}delete_user_meta($user->ID,'tab_flow');$url=EZINV_Invoice::invoice_url($token);$kb=TAB_Telegram::inline(array(array(array('text'=>self::t($lang,'open_invoice'),'url'=>$url))));TAB_Telegram::send($chat,sprintf(self::t($lang,'invoice_done'),$id),$kb);}
	private static function orders($chat,$lang){if(!function_exists('wc_get_orders')){TAB_Telegram::send($chat,self::t($lang,'wc_missing'));return;}$rows=array();foreach(wc_get_orders(array('limit'=>5,'orderby'=>'date','order'=>'DESC'))as$o){$url=$o->get_edit_order_url();$rows[]=array(array('text'=>'#'.$o->get_id().' — '.wp_strip_all_tags($o->get_formatted_order_total()),'url'=>$url));}TAB_Telegram::send($chat,self::t($lang,'orders'),TAB_Telegram::inline($rows));}
	private static function status($chat,$lang){TAB_Telegram::send($chat,self::t($lang,'online')."\nWordPress: ".get_bloginfo('version')."\nWooCommerce: ".(class_exists('WooCommerce')?'ON':'OFF')."\nTahanoa Invoice: ".(class_exists('EZINV_DB')?'ON':'OFF'));}
	private static function connect($chat,$code,$m){$r=get_transient('tab_pair_'.sanitize_key($code));if(!is_array($r)||empty($r['user_id'])||!user_can($r['user_id'],'manage_options')){TAB_Telegram::send($chat,'Invalid or expired connection code.');return;}update_user_meta($r['user_id'],'tab_telegram_chat_id',$chat);update_user_meta($r['user_id'],'tab_telegram_username',sanitize_text_field($m['from']['username']??''));delete_transient('tab_pair_'.sanitize_key($code));TAB_Telegram::send($chat,self::t(TAB_Plugin::settings()['language'],'menu'),TAB_Telegram::menu(TAB_Plugin::settings()['language']));}
	private static function user($chat){$u=get_users(array('meta_key'=>'tab_telegram_chat_id','meta_value'=>$chat,'number'=>1));return !empty($u)&&user_can($u[0]->ID,'manage_options')?$u[0]:false;}
	private static function lang($u){return get_user_meta($u->ID,'tab_language',true)?:TAB_Plugin::settings()['language'];}
	private static function save_invoice($id,$step,$data){update_user_meta($id,'tab_flow',array('type'=>'invoice','step'=>$step,'data'=>$data,'updated'=>time()));}
	private static function number($v){$v=strtr($v,array('۰'=>'0','۱'=>'1','۲'=>'2','۳'=>'3','۴'=>'4','۵'=>'5','۶'=>'6','۷'=>'7','۸'=>'8','۹'=>'9','٬'=>'',','=>''));return absint(preg_replace('/[^0-9]/','',$v));}
	private static function t($l,$k){$x=array('menu'=>array('منوی مدیریت را انتخاب کنید.','Choose an administration action.'),'cancelled'=>array('فرایند لغو شد.','Process cancelled.'),'online'=>array('سایت فعال است.','Site is online.'),'orders'=>array('سفارش‌های اخیر','Recent orders'),'wc_missing'=>array('ووکامرس فعال نیست.','WooCommerce is not active.'),'invoice_missing'=>array('افزونه صورتحساب فعال نیست.','Invoice plugin is not active.'),'inv_title'=>array('عنوان صورتحساب را ارسال کنید.','Send the invoice title.'),'inv_amount'=>array('مبلغ را به تومان ارسال کنید.','Send the amount in Toman.'),'inv_customer'=>array('نام مشتری را ارسال کنید.','Send the customer name.'),'inv_mobile'=>array('شماره موبایل را ارسال کنید.','Send the mobile number.'),'inv_description'=>array('توضیحات را ارسال کنید.','Send the description.'),'bad_title'=>array('عنوان معتبر وارد کنید.','Enter a valid title.'),'bad_amount'=>array('مبلغ معتبر وارد کنید.','Enter a valid amount.'),'bad_mobile'=>array('شماره موبایل معتبر نیست.','Invalid mobile number.'),'skip'=>array('ردکردن','Skip'),'back'=>array('مرحله قبل','Previous step'),'cancel'=>array('لغو','Cancel'),'confirm'=>array('تأیید نهایی','Final confirmation'),'review'=>array('اطلاعات صورتحساب را بررسی کنید:','Review the invoice:'),'toman'=>array('تومان','Toman'),'open_invoice'=>array('بازکردن صورتحساب','Open invoice'),'invoice_done'=>array('صورتحساب #%d ساخته شد.','Invoice #%d was created.'));return $x[$k]['fa'===$l?0:1]??$k;}
}
