<?php
defined( 'ABSPATH' ) || exit;

final class TAB_Admin {
	public static function boot(){add_action('admin_menu',array(__CLASS__,'menu'));add_action('admin_init',array(__CLASS__,'save'));add_action('admin_enqueue_scripts',array(__CLASS__,'assets'));}
	public static function menu(){
		add_menu_page('TeleAdmin Bridge','TeleAdmin','manage_options','teleadmin-bridge',array(__CLASS__,'bot_page'),'dashicons-format-chat',58);
		add_submenu_page('teleadmin-bridge','Bot configuration',self::label('bot_menu'),'manage_options','teleadmin-bridge',array(__CLASS__,'bot_page'));
		add_submenu_page('teleadmin-bridge','Administrator connection',self::label('connection_menu'),'manage_options','teleadmin-connection',array(__CLASS__,'connection_page'));
		add_submenu_page('teleadmin-bridge','Integrations',self::label('integrations_menu'),'manage_options','teleadmin-integrations',array(__CLASS__,'integrations_page'));
	}
	public static function assets($hook){if(false!==strpos($hook,'teleadmin')){wp_enqueue_style('tab-admin',TAB_URL.'assets/admin.css',array(),TAB_VERSION);wp_enqueue_style('tab-admin-v12',TAB_URL.'assets/admin-v12.css',array('tab-admin'),TAB_VERSION);}}
	public static function save(){
		if(empty($_POST['tab_action'])||!current_user_can('manage_options'))return;check_admin_referer('tab_save');$a=sanitize_key(wp_unslash($_POST['tab_action']));$s=TAB_Plugin::settings();
		if('save_bot'===$a){$s['bot_token']=trim(sanitize_text_field(wp_unslash($_POST['bot_token']??'')));$s['language']=in_array($_POST['language']??'',array('fa','en'),true)?$_POST['language']:'fa';update_option(TAB_Plugin::OPTION,$s,false);$me=TAB_Telegram::request('getMe');if(is_wp_error($me))add_settings_error('tab','api',$me->get_error_message(),'error');else{$s['bot_username']=sanitize_text_field($me['username']);update_option(TAB_Plugin::OPTION,$s,false);$r=self::configure($s);add_settings_error('tab',is_wp_error($r)?'hook':'saved',is_wp_error($r)?$r->get_error_message():self::t('configured'),is_wp_error($r)?'error':'success');}}
		if('save_integrations'===$a){$s['notify_orders']=empty($_POST['notify_orders'])?0:1;$s['notify_invoices']=empty($_POST['notify_invoices'])?0:1;$s['delete_data']=empty($_POST['delete_data'])?0:1;update_option(TAB_Plugin::OPTION,$s,false);add_settings_error('tab','saved',self::t('saved'),'success');}
		if('disconnect'===$a){self::delete_user_connection(get_current_user_id());add_settings_error('tab','disconnected',self::t('disconnected'),'success');}
	}
	private static function configure($s){$r=TAB_Telegram::request('setWebhook',array('url'=>rest_url('teleadmin/v1/webhook/'.$s['secret']),'secret_token'=>$s['secret'],'allowed_updates'=>wp_json_encode(array('message','callback_query'))));if(is_wp_error($r))return $r;TAB_Telegram::request('setMyCommands',array('commands'=>wp_json_encode(array(array('command'=>'start','description'=>'Open admin menu'),array('command'=>'status','description'=>'Site status'),array('command'=>'cancel','description'=>'Cancel current process')))));TAB_Telegram::request('setMyName',array('name'=>mb_substr(wp_specialchars_decode(get_bloginfo('name')),0,64)));return true;}
	private static function delete_user_connection($id){foreach(array('tab_telegram_chat_id','tab_telegram_username','tab_language','tab_flow')as$k)delete_user_meta($id,$k);}
	private static function lang(){if(isset($_GET['ui_lang'])&&in_array($_GET['ui_lang'],array('fa','en'),true))update_user_meta(get_current_user_id(),'tab_admin_language',sanitize_key($_GET['ui_lang']));return get_user_meta(get_current_user_id(),'tab_admin_language',true)==='en'?'en':'fa';}
	private static function label($key){return self::t($key);}
	private static function shell($title,$icon,$content){
		$l=self::lang();$rtl='fa'===$l;$chat=get_user_meta(get_current_user_id(),'tab_telegram_chat_id',true);settings_errors('tab');?>
		<div class="wrap tab-wrap <?php echo $rtl?'tab-rtl':'';?>"><header><div class="tab-brand"><span class="dashicons <?php echo esc_attr($icon);?> tab-logo"></span><div><h1><?php echo esc_html($title);?></h1><p><?php echo esc_html(self::t('subtitle'));?></p></div></div><div class="tab-head-actions"><a class="tab-lang" href="<?php echo esc_url(add_query_arg('ui_lang',$rtl?'en':'fa'));?>"><?php echo $rtl?'English':'فارسی';?></a><span class="tab-pill <?php echo $chat?'ok':'';?>"><?php echo esc_html(self::t($chat?'connected':'not_connected'));?></span></div></header><main class="tab-page"><?php call_user_func($content);?></main><footer><?php echo esc_html(self::t('security'));?></footer></div><?php
	}
	public static function bot_page(){self::shell(self::t('bot_title'),'dashicons-admin-settings',array(__CLASS__,'bot_content'));}
	public static function bot_content(){$s=TAB_Plugin::settings();?><section class="tab-card"><div class="tab-section-head"><span class="dashicons dashicons-admin-network"></span><div><h2><?php echo esc_html(self::t('bot_heading'));?></h2><p><?php echo esc_html(self::t('bot_help'));?></p></div></div><form method="post"><?php wp_nonce_field('tab_save');?><input type="hidden" name="tab_action" value="save_bot"><div class="tab-field"><label>BotFather Token</label><input class="regular-text code" dir="ltr" type="password" autocomplete="new-password" name="bot_token" value="<?php echo esc_attr($s['bot_token']);?>" placeholder="123456789:AA..."></div><div class="tab-field"><label><?php echo esc_html(self::t('bot_language'));?></label><select name="language"><option value="fa" <?php selected($s['language'],'fa');?>>فارسی</option><option value="en" <?php selected($s['language'],'en');?>>English</option></select></div><?php submit_button(self::t('save_config'),'primary large');?></form></section><section class="tab-card tab-info"><div class="tab-section-head"><span class="dashicons dashicons-info-outline"></span><div><h2><?php echo esc_html(self::t('requirements'));?></h2><p><?php echo esc_html(self::t('https_help'));?></p></div></div></section><?php }
	public static function connection_page(){self::shell(self::t('connection_title'),'dashicons-lock',array(__CLASS__,'connection_content'));}
	public static function connection_content(){$s=TAB_Plugin::settings();$chat=get_user_meta(get_current_user_id(),'tab_telegram_chat_id',true);$user=get_user_meta(get_current_user_id(),'tab_telegram_username',true);$code=wp_generate_password(24,false,false);set_transient('tab_pair_'.sanitize_key($code),array('user_id'=>get_current_user_id()),10*MINUTE_IN_SECONDS);$deep=!empty($s['bot_username'])?'https://t.me/'.rawurlencode($s['bot_username']).'?start=connect_'.rawurlencode($code):'';?><section class="tab-card tab-connect"><?php if($chat):?><div class="tab-connected-box"><span class="dashicons dashicons-yes-alt"></span><div><strong><?php echo esc_html(self::t('connected_ok'));?></strong><p dir="ltr"><?php echo $user?'@'.esc_html($user):esc_html($chat);?></p></div></div><form method="post"><?php wp_nonce_field('tab_save');?><input type="hidden" name="tab_action" value="disconnect"><?php submit_button(self::t('disconnect'),'secondary');?></form><?php elseif($deep):?><span class="dashicons dashicons-admin-users tab-hero-icon"></span><h2><?php echo esc_html(self::t('pair_heading'));?></h2><p><?php echo esc_html(self::t('pair_help'));?></p><a class="button button-primary button-hero" href="<?php echo esc_url($deep);?>" target="_blank" rel="noopener noreferrer"><?php echo esc_html(self::t('connect_button'));?></a><p class="description"><?php echo esc_html(self::t('expires'));?></p><?php else:?><div class="tab-warning"><span class="dashicons dashicons-warning"></span><?php echo esc_html(self::t('save_first'));?></div><?php endif;?></section><?php }
	public static function integrations_page(){self::shell(self::t('integrations_title'),'dashicons-admin-plugins',array(__CLASS__,'integrations_content'));}
	public static function integrations_content(){$s=TAB_Plugin::settings();?><section class="tab-card"><div class="tab-status"><span>WordPress <b class="on">Active</b></span><span>WooCommerce <b class="<?php echo class_exists('WooCommerce')?'on':'off';?>"><?php echo class_exists('WooCommerce')?'Active':'Inactive';?></b></span><span>Tahanoa Invoice <b class="<?php echo class_exists('EZINV_DB')?'on':'off';?>"><?php echo class_exists('EZINV_DB')?'Active':'Inactive';?></b></span><span>Telegram Webhook <b class="<?php echo !empty($s['bot_username'])?'on':'off';?>"><?php echo !empty($s['bot_username'])?'Configured':'Not configured';?></b></span></div><form method="post" class="tab-toggles"><?php wp_nonce_field('tab_save');?><input type="hidden" name="tab_action" value="save_integrations"><label><input type="checkbox" name="notify_orders" value="1" <?php checked($s['notify_orders']);?>><span><strong><?php echo esc_html(self::t('order_notifications'));?></strong><small><?php echo esc_html(self::t('order_help'));?></small></span></label><label><input type="checkbox" name="notify_invoices" value="1" <?php checked($s['notify_invoices']);?>><span><strong><?php echo esc_html(self::t('invoice_notifications'));?></strong><small><?php echo esc_html(self::t('invoice_help'));?></small></span></label><label><input type="checkbox" name="delete_data" value="1" <?php checked(!empty($s['delete_data']));?>><span><strong><?php echo esc_html(self::t('delete_data'));?></strong><small><?php echo esc_html(self::t('delete_help'));?></small></span></label><?php submit_button(self::t('save_settings'),'primary large');?></form></section><?php }
	private static function t($k){$l=self::lang();$x=array(
	'bot_menu'=>array('پیکربندی ربات','Bot configuration'),'connection_menu'=>array('اتصال مدیر','Administrator connection'),'integrations_menu'=>array('یکپارچه‌سازی‌ها','Integrations'),'subtitle'=>array('مدیریت امن وردپرس از طریق تلگرام','Secure WordPress administration through Telegram'),'connected'=>array('مدیر متصل است','Admin connected'),'not_connected'=>array('متصل نشده','Not connected'),'bot_title'=>array('پیکربندی ربات','Bot configuration'),'bot_heading'=>array('اتصال به BotFather','Connect to BotFather'),'bot_help'=>array('توکن ربات را وارد کنید تا Webhook، نام سایت و فرمان‌ها پیکربندی شوند.','Enter the bot token to configure the webhook, site name, and commands.'),'bot_language'=>array('زبان پیش‌فرض ربات','Default bot language'),'save_config'=>array('ذخیره و پیکربندی','Save and configure'),'requirements'=>array('پیش‌نیاز اتصال','Connection requirements'),'https_help'=>array('سایت باید HTTPS معتبر و REST API قابل دسترس داشته باشد.','The site needs valid HTTPS and a reachable REST API.'),'connection_title'=>array('اتصال مدیر','Administrator connection'),'connected_ok'=>array('حساب تلگرام این مدیر متصل است.','This administrator’s Telegram account is connected.'),'disconnect'=>array('قطع اتصال حساب','Disconnect account'),'pair_heading'=>array('اتصال امن حساب تلگرام','Secure Telegram pairing'),'pair_help'=>array('پیوند یک‌بارمصرف زیر را باز کنید تا حساب مدیر فعلی متصل شود.','Open the one-time link below to connect the current administrator.'),'connect_button'=>array('اتصال با تلگرام','Connect with Telegram'),'expires'=>array('پیوند پس از ۱۰ دقیقه منقضی می‌شود.','The link expires after 10 minutes.'),'save_first'=>array('ابتدا توکن معتبر ربات را در بخش پیکربندی ذخیره کنید.','Save a valid bot token in Bot configuration first.'),'integrations_title'=>array('یکپارچه‌سازی‌ها','Integrations'),'order_notifications'=>array('اعلان سفارش‌های ووکامرس','WooCommerce order notifications'),'order_help'=>array('سفارش‌های جدید و تغییر وضعیت آن‌ها ارسال شود.','Send new orders and order status changes.'),'invoice_notifications'=>array('اعلان پرداخت صورتحساب','Invoice payment notifications'),'invoice_help'=>array('پرداخت موفق صورتحساب برای مدیران ارسال شود.','Send successful invoice payments to administrators.'),'delete_data'=>array('حذف کامل اطلاعات هنگام پاک‌کردن افزونه','Remove all data when uninstalling'),'delete_help'=>array('تنظیمات، اتصال مدیران، فرایندها و داده‌های داخلی TeleAdmin پاک شوند.','Delete settings, administrator connections, flows, and internal TeleAdmin data.'),'save_settings'=>array('ذخیره تنظیمات','Save settings'),'security'=>array('فقط مدیران دارای دسترسی manage_options امکان اتصال و اجرای فرمان دارند.','Only administrators with manage_options can connect and execute commands.'),'configured'=>array('ربات و Webhook پیکربندی شدند.','Bot and webhook configured.'),'saved'=>array('تنظیمات ذخیره شد.','Settings saved.'),'disconnected'=>array('اتصال مدیر قطع شد.','Administrator disconnected.'));return $x[$k]['fa'===$l?0:1]??$k;}
}
